modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="empyrealinterface"
version="0.2.4-alpha"
displayName="Empyreal Interface"
description=""
authors="niki119"
[[dependencies.empyrealinterface]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.empyrealinterface]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"