modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="empyrealinterface"
version="0.2.5-alpha"
displayName="EmpyrealInterface"
description="Empyreal Interface"
authors="niki119"